const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto')
const {DurableQueue,looksLikeLog,MAX_BYTES}=require('../queue.cjs')
const key=crypto.randomBytes(32)
const cipher={encrypt:async text=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key,iv);const encrypted=Buffer.concat([c.update(text),c.final()]);return Buffer.concat([iv,c.getAuthTag(),encrypted])},decrypt:async data=>{const c=crypto.createDecipheriv('aes-256-gcm',key,data.subarray(0,12));c.setAuthTag(data.subarray(12,28));return Buffer.concat([c.update(data.subarray(28)),c.final()]).toString()}}
const log="Alice drew 7 cards for the opening hand.\nBob drew 7 cards for the opening hand.\nTurn # 1 - Alice's Turn\nAlice played Dragapult ex.\nAlice wins."
async function fixture(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'desktop-queue-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const q=new DurableQueue(path.join(dir,'queue.enc'),cipher);await q.load();return q}
test('recognizes numbered and possessive turns; ignores unrelated and oversized clipboard',()=>{assert.ok(looksLikeLog(log));assert.ok(looksLikeLog(log.replace("Turn # 1 - Alice's Turn","Alice’s Turn")));assert.equal(looksLikeLog('password=do-not-store'),false);assert.equal(looksLikeLog(log+'x'.repeat(MAX_BYTES)),false)})
test('encrypts before persistence and survives restart without an acknowledgement',async t=>{const q=await fixture(t);await q.add(log,'a','Alice');const bytes=await fs.readFile(q.file);assert.equal(bytes.includes(Buffer.from(log)),false);const restored=new DurableQueue(q.file,cipher);await restored.load();assert.equal(restored.next('a').rawLog,log);assert.equal(restored.next('b'),undefined)})
test('serializes concurrent duplicate captures and preserves different owners',async t=>{const q=await fixture(t);await Promise.all([q.add(log,'a','Alice'),q.add(log.replace(/ /g,'  '),'a','Alice'),q.add(log,'b','Bob')]);assert.equal(q.data.entries.length,2)})
test('acknowledgement cannot remove another account queue',async t=>{const q=await fixture(t);await q.add(log,'a','Alice');const id=q.next('a').id;await q.acknowledge(id,'b');assert.equal(q.data.entries.length,1);await q.acknowledge(id,'a');assert.equal(q.data.entries.length,0)})
test('failed writes preserve memory and previous encrypted file',async t=>{const q=await fixture(t);await q.add(log,'a','Alice');const previous=await fs.readFile(q.file);q.crypto={...cipher,encrypt:async()=>{throw Error('disk/crypto failed')}};await assert.rejects(q.configure({enabled:true}));assert.equal(q.data.settings.enabled,false);assert.deepEqual(await fs.readFile(q.file),previous)})
test('retry backoff, review and explicit retry retain raw data',async t=>{const q=await fixture(t);await q.add(log,'a','Alice');const id=q.next('a').id;await q.fail(id,'a','offline');assert.equal(q.next('a'),undefined);await q.fail(id,'a','Unknown player',true);assert.equal(q.next('a',Infinity),undefined);await assert.rejects(q.review(id,'b','Bob'));await q.review(id,'a','Alice');assert.equal(q.next('a').rawLog,log)})
test('corrupt queue fails closed without overwriting evidence',async t=>{const q=await fixture(t);await fs.writeFile(q.file,'corrupt');await assert.rejects(q.load(),/preserved/);assert.equal(await fs.readFile(q.file,'utf8'),'corrupt')})
